# Generated by Django 5.1.4 on 2025-02-09 08:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('url', models.URLField(max_length=1000)),
                ('url_to_image', models.URLField(blank=True, max_length=1000, null=True)),
                ('published_at', models.DateTimeField()),
                ('source_name', models.CharField(max_length=500)),
                ('embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('language', models.CharField(default='en', max_length=10)),
            ],
        ),
    ]
